export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';

export const FETCH_ANIMALS= 'FETCH_ANIMALS';
export const RECEIVE_ALL_ANIMALS = 'RECEIVE_ALL_ANIMALS';
export const RECEIVE_ANIMAL_BY_ID = 'RECEIVE_ANIMAL_BY_ID';
export const RECEIVE_ANIMALS_BY_USER_ID = 'RECEIVE_ANIMALS_BY_USER_ID';
export const RECEIVE_ANIMAL_CERTIFICATES = 'RECEIVE_ANIMAL_CERTIFICATES';
export const RECEIVE_ANIMAL_FORMS = 'RECEIVE_ANIMAL_FORMS';
export const RECEIVE_ANIMAL_VACCINATIONS = 'RECEIVE_ANIMAL_VACCINATIONS';


export const RECEIVE_ALL_FORMS = 'RECEIVE_ALL_FORMS';

export const RECEIVE_ALL_CERTIFICATES = 'RECEIVE_ALL_CERTIFICATES';

export const RECEIVE_ALL_VACCINATIONS = 'RECEIVE_ALL_VACCINATIONS';